/** @format */

export default [
	{
		login: 'Ajibolarilwan14',
		id: 45234361,
		node_id: 'MDQ6VXNlcjQ1MjM0MzYx',
		avatar_url: 'https://avatars3.githubusercontent.com/u/45234361?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Ajibolarilwan14',
		html_url: 'https://github.com/Ajibolarilwan14',
		followers_url: 'https://api.github.com/users/Ajibolarilwan14/followers',
		following_url:
			'https://api.github.com/users/Ajibolarilwan14/following{/other_user}',
		gists_url: 'https://api.github.com/users/Ajibolarilwan14/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/Ajibolarilwan14/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/Ajibolarilwan14/subscriptions',
		organizations_url: 'https://api.github.com/users/Ajibolarilwan14/orgs',
		repos_url: 'https://api.github.com/users/Ajibolarilwan14/repos',
		events_url: 'https://api.github.com/users/Ajibolarilwan14/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/Ajibolarilwan14/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Shipow',
		id: 976175,
		node_id: 'MDQ6VXNlcjk3NjE3NQ==',
		avatar_url: 'https://avatars3.githubusercontent.com/u/976175?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Shipow',
		html_url: 'https://github.com/Shipow',
		followers_url: 'https://api.github.com/users/Shipow/followers',
		following_url: 'https://api.github.com/users/Shipow/following{/other_user}',
		gists_url: 'https://api.github.com/users/Shipow/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/Shipow/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/Shipow/subscriptions',
		organizations_url: 'https://api.github.com/users/Shipow/orgs',
		repos_url: 'https://api.github.com/users/Shipow/repos',
		events_url: 'https://api.github.com/users/Shipow/events{/privacy}',
		received_events_url: 'https://api.github.com/users/Shipow/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'segebee',
		id: 629212,
		node_id: 'MDQ6VXNlcjYyOTIxMg==',
		avatar_url: 'https://avatars1.githubusercontent.com/u/629212?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/segebee',
		html_url: 'https://github.com/segebee',
		followers_url: 'https://api.github.com/users/segebee/followers',
		following_url: 'https://api.github.com/users/segebee/following{/other_user}',
		gists_url: 'https://api.github.com/users/segebee/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/segebee/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/segebee/subscriptions',
		organizations_url: 'https://api.github.com/users/segebee/orgs',
		repos_url: 'https://api.github.com/users/segebee/repos',
		events_url: 'https://api.github.com/users/segebee/events{/privacy}',
		received_events_url: 'https://api.github.com/users/segebee/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Knezaregis',
		id: 45655360,
		node_id: 'MDQ6VXNlcjQ1NjU1MzYw',
		avatar_url: 'https://avatars1.githubusercontent.com/u/45655360?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Knezaregis',
		html_url: 'https://github.com/Knezaregis',
		followers_url: 'https://api.github.com/users/Knezaregis/followers',
		following_url:
			'https://api.github.com/users/Knezaregis/following{/other_user}',
		gists_url: 'https://api.github.com/users/Knezaregis/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/Knezaregis/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/Knezaregis/subscriptions',
		organizations_url: 'https://api.github.com/users/Knezaregis/orgs',
		repos_url: 'https://api.github.com/users/Knezaregis/repos',
		events_url: 'https://api.github.com/users/Knezaregis/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/Knezaregis/received_events',
		type: 'User',
		site_admin: false,
	},
];
